### ISSUE TITLE
Image isn't available on ecr-public

### ISSUE THREAD

**Issue by aaronmell** [aws/aws-network-policy-agent#98] opened 2023-10-17 17:15 UTC
It would be nice if this image was added to the ECR image repository like the other CNI images are, so folks that use ECR can pull this image into their own account.

**Comment by jdn5126** [comment] 2023-10-31 21:54
Duplicate of https://github.com/aws/aws-network-policy-agent/issues/119, this issue is complete

**Closed by jdn5126** 2023-10-31 21:54 UTC
Labels: enhancement
