### ISSUE TITLE
please remove python2.7 from the network-policy agent

### ISSUE THREAD

**Issue by maxres-ch** [aws/aws-network-policy-agent#109] opened 2023-10-24 16:26 UTC
**What would you like to be added**:
I don't want anything added, I want something removed.
Current python2.7 is the network policy agent.
```
❯ k exec -it -n kube-system aws-node-wt6mn -c aws-eks-nodeagent -- bash
bash-4.2# python2.7
Python 2.7.18 (default, Feb 28 2023, 02:51:06)
[GCC 7.3.1 20180712 (Red Hat 7.3.1-15)] on linux2
Type "help", "cop
```
**Why is this needed**:

We run in a regulated environment python2.7 has open CVEs that wont be resolved and now we have audit and infosec demanding that we fix the CVEs.

**Comment by jdn5126** [comment] 2023-10-24 16:32
Transferred to Network Policy agent repo

**Comment by jdn5126** [comment] 2023-10-24 16:35
@maxres-ch this comes from the AL2 base image, I assume: https://github.com/aws/aws-network-policy-agent/blob/main/Dockerfile#L32

I don't see an issue with uninstalling python2.7, as it is not actually used

**Comment by jayanthvn** [comment] 2023-10-24 16:49
This is a duplicate of #107.

**Comment by maxres-ch** [comment] 2023-10-24 17:31
@jdn5126 should I open a PR?

**Comment by jdn5126** [comment] 2023-10-24 18:58
> @jdn5126 should I open a PR?

sure, that would be great, thank you! You are just planning to yum uninstall it?

**Comment by maxres-ch** [comment] 2023-10-24 19:58
> You are just planning to yum uninstall it? 

I was. I don't `yum` much but, I'll try to see how deps can be uninstalled, how that does feel a bit dangerous I'm not sure what kind of existing test coverage that would catch it there.

FWIW I might do this via my personal account @grumps.

**Comment by grumps** [comment] 2023-11-06 04:59
@jdn5126 I looked into this. It looks like the image is based on AL2 and within it yum requires python2.7.  It can't be removed until the base image moves to AL 2023.

**Comment by maxres-ch** [comment] 2023-11-06 16:55
Any chance you know when/if https://github.com/aws/aws-network-policy-agent/blob/main/Dockerfile#L44

Will move to AL 2023, there's no python2.7 here.

**Comment by jdn5126** [comment] 2023-11-07 15:42
I see, thank you for the investigation. I did not realize that AL2 had a hard dependency on Python 2.7. I am not sure about the feasibility of the Network Policy agent moving to AL2023 or to a minimum image build. @jayanthvn @achevuru any thoughts here?

**Comment by jdn5126** [comment] 2023-11-07 20:18
@maxres-ch as a side note, it is my understanding that AL2 is still providing patches for any Python 2.7 CVEs that are discovered, so even as we look to remove it from the image, you shouldn't have CVEs that will never be resolved. Can you share which CVEs you see and against which Network Policy agent image?

It sounds like you already have a support case open through your TAM, can you please share the details there for security reasons?

**Comment by maxres-ch** [comment] 2023-11-07 20:33
Thanks @jdn5126  sounds like they already reached out. Good to know that they are patching it. Means it's likely infosecs tooling problem. I'll send them the CVEs.

**Comment by maxres-ch** [comment] 2023-11-09 14:21
Thanks for your responsiveness @jdn5126

**Closed** 2023-11-09 14:21 UTC
Labels: enhancement

**Comment by jdn5126** [comment] 2023-11-09 16:54
@maxres-ch For the long term, we are still working on moving the image to minimal bases that do not contain Python2.7, as it is not used by the application. These minimal bases will also decrease the surface area for CVEs in general. We are scoping that work out now, as the complexity comes from compiling eBPF programs in a minimal environment.

**Comment by maxres-ch** [comment] 2023-11-10 19:40
Thanks! It totally makes sense that this would be non-trivial. It took a long time to build locally.

I will battle this out with the infosec team for exceptions. Thanks for your efforts.

IMPORTANT NOTICE: This communication, including any attachment, contains information that may be confidential or privileged, and is intended solely for the entity or individual to whom it is addressed.  If you are not the intended recipient, you should delete this message and are hereby notified that any disclosure, copying, or distribution of this message is strictly prohibited.  Nothing in this email, including any attachment, is intended to be a legally binding signature.
